version: '3.9'

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./config/config.yaml:/app/config.yaml
      - ./migrations:/app/migrations
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: notesdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

