// Code generated by MockGen. DO NOT EDIT.
// Source: authService.go

// Package mock is a generated GoMock package.
package mock

import (
	model "Notes/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAbstractAuthService is a mock of AbstractAuthService interface.
type MockAbstractAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAbstractAuthServiceMockRecorder
}

// MockAbstractAuthServiceMockRecorder is the mock recorder for MockAbstractAuthService.
type MockAbstractAuthServiceMockRecorder struct {
	mock *MockAbstractAuthService
}

// NewMockAbstractAuthService creates a new mock instance.
func NewMockAbstractAuthService(ctrl *gomock.Controller) *MockAbstractAuthService {
	mock := &MockAbstractAuthService{ctrl: ctrl}
	mock.recorder = &MockAbstractAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAbstractAuthService) EXPECT() *MockAbstractAuthServiceMockRecorder {
	return m.recorder
}

// AuthUser mocks base method.
func (m *MockAbstractAuthService) AuthUser(login, password string) (string, *model.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthUser", login, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*model.ApplicationError)
	return ret0, ret1
}

// AuthUser indicates an expected call of AuthUser.
func (mr *MockAbstractAuthServiceMockRecorder) AuthUser(login, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthUser", reflect.TypeOf((*MockAbstractAuthService)(nil).AuthUser), login, password)
}

// ValidateToken mocks base method.
func (m *MockAbstractAuthService) ValidateToken(token string) (*model.Claims, *model.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", token)
	ret0, _ := ret[0].(*model.Claims)
	ret1, _ := ret[1].(*model.ApplicationError)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockAbstractAuthServiceMockRecorder) ValidateToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockAbstractAuthService)(nil).ValidateToken), token)
}
