// Code generated by MockGen. DO NOT EDIT.
// Source: jwtService.go

// Package mock is a generated GoMock package.
package mock

import (
	model "Notes/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAbstractJwtService is a mock of AbstractJwtService interface.
type MockAbstractJwtService struct {
	ctrl     *gomock.Controller
	recorder *MockAbstractJwtServiceMockRecorder
}

// MockAbstractJwtServiceMockRecorder is the mock recorder for MockAbstractJwtService.
type MockAbstractJwtServiceMockRecorder struct {
	mock *MockAbstractJwtService
}

// NewMockAbstractJwtService creates a new mock instance.
func NewMockAbstractJwtService(ctrl *gomock.Controller) *MockAbstractJwtService {
	mock := &MockAbstractJwtService{ctrl: ctrl}
	mock.recorder = &MockAbstractJwtServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAbstractJwtService) EXPECT() *MockAbstractJwtServiceMockRecorder {
	return m.recorder
}

// GetToken mocks base method.
func (m *MockAbstractJwtService) GetToken(id int) (string, *model.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToken", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*model.ApplicationError)
	return ret0, ret1
}

// GetToken indicates an expected call of GetToken.
func (mr *MockAbstractJwtServiceMockRecorder) GetToken(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MockAbstractJwtService)(nil).GetToken), id)
}

// ParseToken mocks base method.
func (m *MockAbstractJwtService) ParseToken(tokenString string) (*model.Claims, *model.ApplicationError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseToken", tokenString)
	ret0, _ := ret[0].(*model.Claims)
	ret1, _ := ret[1].(*model.ApplicationError)
	return ret0, ret1
}

// ParseToken indicates an expected call of ParseToken.
func (mr *MockAbstractJwtServiceMockRecorder) ParseToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseToken", reflect.TypeOf((*MockAbstractJwtService)(nil).ParseToken), tokenString)
}
